"""Image generation + WebP optimization + Vision validation."""
from __future__ import annotations
import base64, io, json, re, time
import urllib.error, urllib.request
from utils import log

MAX_DIM = 1600
WEBP_QUALITY = 82

# Person/people-related words that trigger Imagen safety filter (returns empty predictions
# because of personGeneration: dont_allow). Replace with neutral object-focused phrasing.
PERSON_PATTERNS = [
    (r"\b(mom|mother|mother's|mommy|mum)\b", "tea gift"),
    (r"\b(dad|father|father's|daddy)\b", "tea gift"),
    (r"\b(woman|women|lady|ladies|girl|girls)\b", ""),
    (r"\b(man|men|guy|guys|boy|boys)\b", ""),
    (r"\b(person|people|someone|family|child|children|kid|kids|baby|babies)\b", ""),
    (r"\b(hand|hands|fingers|finger|arm|arms)\b", ""),
    (r"\b(ritual|enjoying|sipping|drinking|holding|pouring)\b", "still life of"),
    (r"\b(her|his|their|she|he|they)\b", "the"),
    (r"\bmorning routine\b", "morning still life"),
    (r"\bself-care\b", "tea setup"),
]


def sanitize_image_prompt(prompt):
    """Remove person references from prompt to avoid Imagen safety filter.
    Returns sanitized prompt; logs if changes were made."""
    original = prompt
    out = prompt
    for pat, repl in PERSON_PATTERNS:
        out = re.sub(pat, repl, out, flags=re.IGNORECASE)
    # collapse double spaces and stray punctuation
    out = re.sub(r"\s+", " ", out).strip()
    out = re.sub(r"\s*,\s*,+", ",", out)
    if out != original:
        log("  프롬프트 정화: 사람 관련 단어 제거됨")
    return out


def _clean_filename(name):
    name = re.sub(r"\.(jpg|jpeg|png|webp|gif|bmp)$", "", name, flags=re.IGNORECASE)
    name = re.sub(r"[^a-z0-9-]+", "-", name.lower())
    return name.strip("-")


class ImagenSafetyBlocked(RuntimeError):
    """Imagen returned empty predictions - prompt likely blocked by safety filter."""
    pass


def generate_imagen(prompt, *, api_key, model="imagen-4.0-generate-001",
                     n=1, aspect_ratio="16:9", max_retries=3):
    url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
           f"{model}:predict?key={api_key}")
    body = json.dumps({
        "instances": [{"prompt": prompt}],
        "parameters": {"sampleCount": n, "aspectRatio": aspect_ratio,
                       "personGeneration": "dont_allow"},
    }).encode("utf-8")
    last_err = None
    for attempt in range(1, max_retries + 1):
        req = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                data = json.loads(resp.read())
            out = []
            for pred in data.get("predictions", []):
                b64 = pred.get("bytesBase64Encoded") or pred.get("imageBytesBase64") or ""
                if b64:
                    out.append(base64.b64decode(b64))
            if out:
                return out
            # empty predictions = safety filter block; retrying same prompt won't help
            raise ImagenSafetyBlocked(
                "empty predictions (safety filter blocked - prompt likely contains person/sensitive content)"
            )
        except ImagenSafetyBlocked:
            raise
        except urllib.error.HTTPError as e:
            body_text = e.read().decode("utf-8", errors="ignore")[:300]
            last_err = f"HTTP {e.code}: {body_text}"
            if e.code in (400, 401, 403):
                raise RuntimeError(f"Imagen API {last_err}")
            log(f"  Imagen 시도 {attempt}/{max_retries} 실패 ({e.code}), {5*attempt}초 후 재시도", "WARN")
            time.sleep(5 * attempt)
        except Exception as e:
            last_err = str(e)
            log(f"  Imagen 시도 {attempt}/{max_retries} 예외, 재시도", "WARN")
            time.sleep(5 * attempt)
    raise RuntimeError(f"Imagen 재시도 모두 실패: {last_err}")


def optimize_to_webp(png_bytes, *, max_dim=MAX_DIM, quality=WEBP_QUALITY):
    try:
        from PIL import Image
    except ImportError:
        log("Pillow 없음", "WARN")
        return png_bytes
    img = Image.open(io.BytesIO(png_bytes))
    if img.mode not in ("RGB", "RGBA"):
        img = img.convert("RGB")
    w, h = img.size
    longest = max(w, h)
    if longest > max_dim:
        scale = max_dim / longest
        img = img.resize((int(w * scale), int(h * scale)), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="WEBP", quality=quality, method=6)
    return buf.getvalue()


def verify_image_matches_prompt(image_bytes, prompt, *, anthropic_key,
                                  model="claude-haiku-4-5-20251001"):
    """Claude Vision으로 이미지가 프롬프트와 맞는지 검증.
    반환: (matches: bool, reason: str)"""
    img_b64 = base64.b64encode(image_bytes).decode("ascii")
    user_text = (
        f"This image was generated by AI from this prompt:\n\n\"" + prompt[:500] + "\"\n\n"
        "Question: Does the image visually MATCH the prompt's described subject? "
        "If the prompt describes food/tea/scones but the image shows something completely "
        "unrelated (vehicles, animals, people, abstract shapes), it does NOT match.\n\n"
        "Reply with ONLY this JSON (no other text):\n"
        "{\"match\": true_or_false, \"reason\": \"brief explanation under 100 chars\"}"
    )
    body = json.dumps({
        "model": model, "max_tokens": 200, "temperature": 0,
        "messages": [{
            "role": "user",
            "content": [
                {"type": "image", "source": {"type": "base64",
                    "media_type": "image/webp", "data": img_b64}},
                {"type": "text", "text": user_text},
            ],
        }],
    }).encode("utf-8")
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages", data=body,
        headers={"x-api-key": anthropic_key, "anthropic-version": "2023-06-01",
                 "content-type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())
    except Exception as e:
        log(f"  비전 검증 실패 (네트워크): {e} — 통과 처리", "WARN")
        return True, "verify_failed_pass"

    text = "".join(p.get("text", "") for p in data.get("content", []) if p.get("type") == "text")
    # Extract JSON
    m = re.search(r"\{[^{}]*\"match\"[^{}]*\}", text)
    if not m:
        log(f"  비전 응답 파싱 실패: {text[:100]} — 통과 처리", "WARN")
        return True, "parse_failed_pass"
    try:
        result = json.loads(m.group(0))
        return bool(result.get("match", True)), str(result.get("reason", ""))[:200]
    except Exception:
        return True, "parse_failed_pass"


def _fallback_prompt(filename_base):
    """If safety filter blocks even the sanitized prompt, build a generic
    object-only fallback from the filename (which is purely descriptive)."""
    keywords = re.sub(r"[-_]+", " ", _clean_filename(filename_base))
    return (
        f"Editorial still life photograph: {keywords}. "
        "No people, no human figures, no body parts. "
        "Soft natural daylight, cream linen background, "
        "shallow depth of field, magazine-quality composition, "
        "warm earthy tones."
    )


def generate_image_for_slot(*, prompt, filename_base, api_key, model,
                              variants=1, aspect_ratio="16:9",
                              anthropic_key=None, max_vision_retries=2):
    """이미지 생성 + 프롬프트 정화 + 비전 검증 + 불일치 시 자동 재생성."""
    clean_name = _clean_filename(filename_base)
    log(f"  이미지 생성 ({variants}장): {clean_name}")

    # Step 1: sanitize prompt to remove person references (Imagen safety filter)
    safe_prompt = sanitize_image_prompt(prompt)

    last_webp = None
    last_png = None
    pngs = []

    def _try_generate(p):
        return generate_imagen(p, api_key=api_key, model=model,
                                n=variants, aspect_ratio=aspect_ratio)

    for vision_try in range(max_vision_retries + 1):
        try:
            pngs = _try_generate(safe_prompt)
        except ImagenSafetyBlocked as e:
            log(f"  ⚠️ 안전 필터 차단됨 ({e}) — 폴백 프롬프트로 재시도", "WARN")
            fb = _fallback_prompt(filename_base)
            log(f"  폴백 프롬프트: {fb[:100]}...")
            try:
                pngs = _try_generate(fb)
            except ImagenSafetyBlocked:
                raise RuntimeError(
                    f"Imagen 안전 필터: 정화 프롬프트와 폴백 모두 차단됨 ({clean_name})"
                )
        if not pngs:
            raise RuntimeError(f"이미지 생성 실패: {safe_prompt[:60]}")
        best = max(pngs, key=len)
        webp = optimize_to_webp(best)
        last_webp = webp
        last_png = best

        if not anthropic_key:
            # 비전 키 없으면 검증 스킵
            log(f"  최적화 완료: {len(best):,}B → {len(webp):,}B ({len(webp)/len(best)*100:.0f}%)")
            break

        # 비전 검증
        log(f"  비전 검증 시도 {vision_try+1}/{max_vision_retries+1}")
        matches, reason = verify_image_matches_prompt(
            webp, safe_prompt, anthropic_key=anthropic_key)
        if matches:
            log(f"  ✅ 비전 검증 통과: {reason}")
            log(f"  최적화: {len(best):,}B → {len(webp):,}B ({len(webp)/len(best)*100:.0f}%)")
            break
        log(f"  ❌ 비전 검증 실패: {reason} — 재생성", "WARN")
        if vision_try == max_vision_retries:
            log(f"  비전 재시도 한도 도달 — 마지막 이미지 사용", "WARN")

    return {"webp_bytes": last_webp, "filename": f"{clean_name}.webp",
            "variants_count": len(pngs)}
